import { createSlice } from '@reduxjs/toolkit';
import conditioner1 from '../images/conditioner1.png';
import conditioner2 from '../images/conditioner2.png';
import conditioner3 from '../images/conditioner3.png';
import conditioner4 from '../images/conditioner4.png';


export const catalogSlice = createSlice({
  name: 'catalog',
  initialState: {
    data: [
      {
        id: 1,
        title: 'MDV Forest Inverter MDSAF-09HRDN8',
        price: '1 690 BYN',
        category: 'wall-mounted',
        square: '25 x 25',
        technology: 'inverter',
        image: conditioner1,
        brand: 'MDV',
      },
      {
        id: 2,
        title: 'TCL Elite TAC-09CHSD/XA71IN',
        price: '1 740 BYN',
        category: 'wall-mounted',
        square: '30 x 30',
        technology: 'on/off',
        image: conditioner2,
        brand: 'TCL',
      },
      {
        id: 3,
        title: 'MDV AURORA ON/OFF MDSA-07HRN8',
        price: '1 119 BYN',
        category: 'mobile',
        square: '50 x 50',
        technology: 'inverter',
        image: conditioner3,
        brand: 'Ballu',
      },
      {
        id: 4,
        title: 'Chigo Moon Inverter CS-21V3G-B181AY8B',
        price: '2 100 BYN',
        category: 'wall-mounted',
        square: '40 x 40',
        technology: 'on/off',
        image: conditioner4,
        brand: 'Chigo',
      },
      {
        id: 5,
        title: 'MDV AURORA ON/OFF MDSA-07HRN8',
        price: '1 119 BYN',
        category: 'mobile',
        square: '50 x 50',
        technology: 'inverter',
        image: conditioner1,
        brand: 'Gree',
      },
      {
        id: 6,
        title: 'Chigo Moon Inverter CS-21V3G-B181AY8B',
        price: '1 100 BYN',
        category: 'wall-mounted',
        square: '35 x 35',
        technology: 'on/off',
        image: conditioner2,
        brand: 'Haeir',
      },
      {
        id: 7,
        title: 'MDV AURORA ON/OFF MDSA-07HRN8',
        price: '1 119 BYN',
        category: 'mobile',
        square: '50 x 50',
        technology: 'inverter',
        image: conditioner3,
        brand: 'Ballu',
      },
      {
        id: 8,
        title: 'Chigo Moon Inverter CS-21V3G-B181AY8B',
        price: '2 100 BYN',
        category: 'wall-mounted',
        square: '40 x 40',
        technology: 'on/off',
        image: conditioner4,
        brand: 'Chigo',
      },
      {
        id: 9,
        title: 'Chigo Moon Inverter CS-21V3G-B181AY8B',
        price: '2 200 BYN',
        category: 'wall-mounted',
        square: '40 x 40',
        technology: 'inverter',
        image: conditioner3,
        brand: 'MDV',
      },
      {
        id: 10,
        title: 'MDV AURORA ON/OFF MDSA-07HRN8',
        price: '1 119 BYN',
        category: 'mobile',
        square: '50 x 50',
        technology: 'inverter',
        image: conditioner3,
        brand: 'Ballu',
      },
      {
        id: 11,
        title: 'Chigo Moon Inverter CS-21V3G-B181AY8B',
        price: '2 100 BYN',
        category: 'wall-mounted',
        square: '40 x 40',
        technology: 'on/off',
        image: conditioner4,
        brand: 'Chigo',
      },
      {
        id: 12,
        title: 'Chigo Moon Inverter CS-21V3G-B18',
        price: '1 900 BYN',
        category: 'wall-mounted',
        square: '>50',
        technology: 'on/off',
        image: conditioner3,
        brand: 'MDV',
      },
      {
        id: 13,
        title: 'Chigo Moon Inverter CS-21V3G-B18',
        price: '1 900 BYN',
        category: 'wall-mounted',
        square: '> 50 x 50',
        technology: 'inverter',
        image: conditioner3,
        brand: 'Haeir',
      },
      {
        id: 14,
        title: 'Chigo Moon Inverter CS-21V3G-B181AY8B',
        price: '2 100 BYN',
        category: 'wall-mounted',
        square: '40 x 40',
        technology: 'on/off',
        image: conditioner4,
        brand: 'Chigo',
      },
      {
        id: 15,
        title: 'Chigo Moon Inverter CS-21V3G-B181AY8B',
        price: '2 200 BYN',
        category: 'wall-mounted',
        square: '40 x 40',
        technology: 'inverter',
        image: conditioner3,
        brand: 'MDV',
      },
      {
        id: 16,
        title: 'MDV AURORA ON/OFF MDSA-07HRN8',
        price: '1 119 BYN',
        category: 'mobile',
        square: '20 x 20',
        technology: 'on/off',
        image: conditioner3,
        brand: 'Ballu',
      },
      {
        id: 17,
        title: 'Chigo Moon Inverter CS-21V3G-B181AY8B',
        price: '2 100 BYN',
        category: 'wall-mounted',
        square: '25 x 25',
        technology: 'inverter',
        image: conditioner4,
        brand: 'Chigo',
      },
      {
        id: 18,
        title: 'Chigo Moon Inverter CS-21V3G',
        price: '1 800 BYN',
        category: 'mobile',
        square: '40 x 40',
        technology: 'inverter',
        image: conditioner3,
        brand: 'MDV',
      },
      {
        id: 19,
        title: 'Chigo Moon Inverter CS-21V3G-B18',
        price: '1 900 BYN',
        category: 'wall-mounted',
        square: '30 x 30',
        technology: 'on/off',
        image: conditioner3,
        brand: 'Haeir',
      },
      {
        id: 20,
        title: 'Chigo Moon Inverter CS-21V3G-B181AY8B',
        price: '2 100 BYN',
        category: 'wall-mounted',
        square: '25 x 25',
        technology: 'on/off',
        image: conditioner4,
        brand: 'Haeir',
      },
      {
        id: 21,
        title: 'Chigo Moon Inverter CS-21V3G',
        price: '1 800 BYN',
        category: 'wall-mounted',
        square: '>50',
        technology: 'inverter',
        image: conditioner3,
        brand: 'MDV',
      },
      {
        id: 22,
        title: 'Chigo Moon Inverter CS-21V3G-B18',
        price: '1 900 BYN',
        category: 'wall-mounted',
        square: '30 x 30',
        technology: 'on/off',
        image: conditioner3,
        brand: 'Haeir',
      },
    ],
    // loading: false,
    // error: null as null | string,
  },
  reducers: {
    setCatalog(state, action) {
      state.data = action.payload;
    },
  },
});

export const { setCatalog } = catalogSlice.actions;
export const catalogReducer = catalogSlice.reducer;
