import dotenv from 'dotenv';
dotenv.config();

import express from 'express';
import cors from 'cors';
import nodemailer from 'nodemailer';
import multer from 'multer';

const storage = multer.memoryStorage();
const upload = multer({ storage });
const app = express();
const PORT = process.env.PORT;

app.use(express.json());
app.use(cors());

const transporter = nodemailer.createTransport({
  service: 'yandex',
  host: 'smtp.yandex.ru',
  port: 465,
  secure: true,
  auth: {
    user: 'maria.shliapa.dev@yandex.ru',
    pass: process.env.PASSWORD,
  },
  tls: {
    rejectUnauthorized: false,
  },
});

app.post('/send-email', upload.none(), async (req, res) => {
  try {
    const { name, phone, email, text, agreement } = req.body;

    const mailOptions = {
      from: 'maria.shliapa.dev@yandex.ru',
      to: 'maria.shliapa.dev@yandex.ru',
      subject: 'Заказ на сайте',
      text: `Имя: ${name}
      \nEmail: ${email}
      \nPhone: ${phone}
      \nText: ${text}
      \nAgreement: ${agreement}`,
    };

    await transporter.sendMail(mailOptions);
    res.status(200).json({ message: 'success' });
  } catch (e) {
    console.log(e);
    res.status(500).json({ message: 'Something went wrong' });
  }
});

////////////////// catalog

app.get('/catalog', (req, res) => {
  res.json([
    {
      id: 1,
      title: 'MDV Forest Inverter MDSAF-09HRDN8',
      category: 'Настенные',
      square: 25,
      technology: 'Инверторная',
      image: '/../src/assets/images/conditioner1.png',
      image_item: '/../src/assets/images/conditioner_item.png',
      brand: 'MDV',
      guarantee: 40,
      price: 1680,

      serviced_area: 35,
      mode: 'Охлаждение',
      cooling_temperature: 'от -10 до +53',
      heating_temperature: 'от -20 до +35',
      indoor_unit_noise: '20-55',
      outdoor_unit_noise: '38',
      indoor_unit_width: 698,
      outdoor_unit_width: 255,
      outdoor_unit_depth: 190,
      add_functions: [
        'Wi-Fi',
        'Пульт дистанционного управления',
        'Регулировка воздушного потока',
        'Регулировка скорости вращения вентилятара 5 ступ.',
        'Таймер включенияя/выключения',
        'Авторестарт после проподания питания',
        'Турбо-режим',
        'Режим "сон"',
        'Осушение воздуха',
        'Самоочистка',
        'УФ-лампа',
        'Ионизатор',
      ],

      made_in: 'Россия',
      manufacturer: 'MDV Forest',
      importer: 'MDV Forest',
    },
    {
      id: 2,
      title: 'TCL Elite TAC-09CHSD/XA71IN',
      category: 'Настенные',
      square: 35,
      technology: 'on/off',
      image: '/../src/assets/images/conditioner2.png',
      image_item: '/../src/assets/images/conditioner_item2.png',
      brand: 'TCL',
      guarantee: 40,
      price: 1750,

      serviced_area: 78,
      mode: 'Охлаждение и вентиляция',
      cooling_temperature: 'от -10 до +53',
      heating_temperature: 'от -20 до +35',
      indoor_unit_noise: '20-55',
      outdoor_unit_noise: '38',
      indoor_unit_width: 698,
      outdoor_unit_width: 255,
      outdoor_unit_depth: 190,
      add_functions: [
        'Пульт дистанционного управления',
        'Регулировка воздушного потока',
        'Регулировка скорости вращения вентилятара 5 ступ.',
        'Таймер включенияя/выключения',
        'Режим "сон"',
        'Осушение воздуха',
        'Самоочистка',
        'УФ-лампа',
        'Ионизатор',
        'Защита от простуды',
      ],

      made_in: 'Китай',
      manufacturer:
        'ТиСиЭл Оверсиас Маркетинг Лимитед, Аламеда Др. Карлос де Ассумпкао, №263, Эдиф. Чайна Сивил Плаза, 5К, Макао, Китай',
      importer: 'ООО "Биоконд", 220020, г. Минск, ул. Короля, 2 оф. 212',
    },
    {
      id: 3,
      title: 'Gree AURORA ON/OFF MDSA-07HRN8',
      category: 'Мобильные',
      square: 25,
      technology: 'Инверторная',
      image: '/../src/assets/images/conditioner1.png',
      image_item: '/../src/assets/images/conditioner_item3.png',
      brand: 'Gree',
      guarantee: 20,
      price: 1480,

      serviced_area: 78,
      mode: 'Охлаждение и вентиляция',
      cooling_temperature: 'от -10 до +53',
      heating_temperature: 'от -20 до +35',
      indoor_unit_noise: '20-55',
      outdoor_unit_noise: '30',
      indoor_unit_width: 690,
      outdoor_unit_width: 255,
      outdoor_unit_depth: 180,
      add_functions: [
        'Wi-Fi',
        'Пульт дистанционного управления',
        'Таймер включенияя/выключения',
        'Режим "сон"',
        'Осушение воздуха',
        'Самоочистка',
        'УФ-лампа',
      ],

      made_in: 'Китай',
      manufacturer:
        'ТиСиЭл Оверсиас Маркетинг Лимитед, Аламеда Др. Карлос де Ассумпкао, №263, Эдиф. Чайна Сивил Плаза, 5К, Макао, Китай',
      importer: 'ООО "Биоконд", 220020, г. Минск, ул. Короля, 2 оф. 212',
    },
    {
      id: 4,
      title: 'Gree Moon Inverter CS-21V3G-B181AY8B',
      category: 'Настенные',
      square: 20,
      technology: 'on/off',
      image: '/../src/assets/images/conditioner4.png',
      image_item: '/../src/assets/images/conditioner_item.png',
      brand: 'Gree',
      guarantee: 24,
      price: 1455,

      serviced_area: 78,
      mode: 'Охлаждение и вентиляция',
      cooling_temperature: 'от -10 до +53',
      heating_temperature: 'от -20 до +35',
      indoor_unit_noise: '20-55',
      outdoor_unit_noise: '40',
      indoor_unit_width: 698,
      outdoor_unit_width: 255,
      outdoor_unit_depth: 170,
      add_functions: [
        'Пульт дистанционного управления',
        'Регулировка воздушного потока',
        'Регулировка скорости вращения вентилятара 5 ступ.',
        'Таймер включенияя/выключения',
        'Авторестарт после проподания питания',
        'Турбо-режим',
        'Режим "сон"',
        'Осушение воздуха',
        'Самоочистка',
        'Подсос свежего воздуха',
        'УФ-лампа',
        'Ионизатор',
        'Защита от простуды',
      ],

      made_in: 'Китай',
      manufacturer:
        'ТиСиЭл Оверсиас Маркетинг Лимитед, Аламеда Др. Карлос де Ассумпкао, №263, Эдиф. Чайна Сивил Плаза, 5К, Макао, Китай',
      importer: 'ООО "Биоконд", 220020, г. Минск, ул. Короля, 2 оф. 212',
    },
    {
      id: 5,
      title: 'Gree AURORA ON/OFF MDSA-07HRN8',
      category: 'Мобильные',
      square: 50,
      technology: 'Инверторная',
      image: '/../src/assets/images/conditioner1.png',
      image_item: '/../src/assets/images/conditioner_item.png',
      brand: 'Gree',
      guarantee: 12,
      price: 1000,

      serviced_area: 75,
      mode: 'Охлаждение и вентиляция',
      cooling_temperature: 'от -10 до +53',
      heating_temperature: 'от -20 до +35',
      indoor_unit_noise: '20-55',
      outdoor_unit_noise: '50',
      indoor_unit_width: 698,
      outdoor_unit_width: 265,
      outdoor_unit_depth: 200,

      add_functions: [
        'Wi-Fi',
        'Пульт дистанционного управления',
        'Регулировка воздушного потока',
        'Регулировка скорости вращения вентилятара 5 ступ.',
        'Таймер включенияя/выключения',
        'Авторестарт после проподания питания',
        'Турбо-режим',
        'Режим "сон"',
        'Самоочистка',
        'Подсос свежего воздуха',
        'Ионизатор',
        'Защита от простуды',
      ],

      made_in: 'Швеция',
      manufacturer: 'ТиСиЭл Лимитед, Аламеда Др. Карлос де Ассумпкао, №263, Эдиф. , 5К, Макао, Швеция',
      importer: 'ООО "Биоконд", 220020, г. Минск, ул. Короля, 2 оф. 212',
    },
    {
      id: 6,
      title: 'Haeir Moon Inverter CS-21V3G-B181AY8B',
      category: 'Настенные',
      square: 35,
      technology: 'on/off',
      image: '/../src/assets/images/conditioner2.png',
      image_item: '/../src/assets/images/conditioner_item2.png',
      brand: 'Haeir',
      guarantee: 12,
      price: 1009,

      serviced_area: 75,
      mode: 'Охлаждение и вентиляция',
      cooling_temperature: 'от -10 до +53',
      heating_temperature: 'от -20 до +35',
      indoor_unit_noise: '20-55',
      outdoor_unit_noise: '50',
      indoor_unit_width: 508,
      outdoor_unit_width: 255,
      outdoor_unit_depth: 190,

      add_functions: [
        'Wi-Fi',
        'Пульт дистанционного управления',
        'Регулировка воздушного потока',
        'Регулировка скорости вращения вентилятара 5 ступ.',
        'Таймер включенияя/выключения',
        'Авторестарт после проподания питания',
        'Турбо-режим',
        'Режим "сон"',
        'Осушение воздуха',
        'Самоочистка',
        'Подсос свежего воздуха',
        'Ионизатор',
      ],

      made_in: 'Швеция',
      manufacturer: 'ТиСиЭл Лимитед, Аламеда Др. Карлос де Ассумпкао, №263, Эдиф. , 5К, Макао, Швеция',
      importer: 'ООО "Биоконд", 220020, г. Минск, ул. Короля, 2 оф. 212',
    },
    {
      id: 7,
      title: 'Ballu AURORA ON/OFF MDSA-07HRN8',
      category: 'Мобильные',
      square: 50,
      technology: 'Инверторная',
      image: '/../src/assets/images/conditioner1.png',
      image_item: '/../src/assets/images/conditioner_item3.png',
      brand: 'Ballu',
      guarantee: 12,
      price: 1119,

      serviced_area: 75,
      mode: 'Охлаждение и вентиляция',
      cooling_temperature: 'от -10 до +53',
      heating_temperature: 'от -20 до +35',
      indoor_unit_noise: '20-55',
      outdoor_unit_noise: '50',
      indoor_unit_width: 688,
      outdoor_unit_width: 230,
      outdoor_unit_depth: 170,

      add_functions: [
        'Wi-Fi',
        'Пульт дистанционного управления',
        'Регулировка воздушного потока',
        'Регулировка скорости вращения вентилятара 5 ступ.',
        'Таймер включенияя/выключения',
        'Авторестарт после проподания питания',
        'Турбо-режим',
        'Режим "сон"',
        'Осушение воздуха',
        'Самоочистка',
        'Ионизатор',
        'Защита от простуды',
      ],

      made_in: 'Швеция',
      manufacturer: 'ТиСиЭл Лимитед, Аламеда Др. Карлос де Ассумпкао, №263, Эдиф. , 5К, Макао, Швеция',
      importer: 'ООО "Биоконд", 220020, г. Минск, ул. Короля, 2 оф. 212',
    },
    {
      id: 8,
      title: 'TCL Moon Inverter CS-21V3G-B181AY8B',
      category: 'Настенные',
      square: 25,
      technology: 'on/off',
      image: '/../src/assets/images/conditioner4.png',
      image_item: '/../src/assets/images/conditioner_item.png',
      brand: 'TCL',
      guarantee: 12,
      price: 1111,

      serviced_area: 45,
      mode: 'Охлаждение и вентиляция',
      cooling_temperature: 'от -10 до +53',
      heating_temperature: 'от -20 до +35',
      indoor_unit_noise: '20-55',
      outdoor_unit_noise: '50',
      indoor_unit_width: 688,
      outdoor_unit_width: 250,
      outdoor_unit_depth: 170,

      add_functions: [
        'Wi-Fi',
        'Пульт дистанционного управления',
        'Регулировка воздушного потока',
        'Регулировка скорости вращения вентилятара 5 ступ.',
        'Таймер включенияя/выключения',
        'Авторестарт после проподания питания',
        'Турбо-режим',
        'Режим "сон"',
        'Осушение воздуха',
        'Самоочистка',
        'Ионизатор',
        'Защита от простуды',
        'Антибактериальный фильтр',
      ],

      made_in: 'Китай',
      manufacturer:
        'ТиСиЭл Оверсиас Маркетинг Лимитед, Аламеда Др. Карлос де Ассумпкао, №263, Эдиф. Чайна Сивил Плаза, 5К, Макао, Китай',
      importer: 'ООО "Биоконд", 220020, г. Минск, ул. Короля, 2 оф. 212',
    },
    {
      id: 9,
      title: 'TCL Moon Inverter CS-21V3G-B181AY8B',
      category: 'Настенные',
      square: 20,
      technology: 'Инверторная',
      image: '/../src/assets/images/conditioner1.png',
      image_item: '/../src/assets/images/conditioner_item2.png',
      brand: 'TCL',
      guarantee: 48,
      price: 3118,

      serviced_area: 45,
      mode: 'Охлаждение и вентиляция',
      cooling_temperature: 'от -10 до +53',
      heating_temperature: 'от -20 до +35',
      indoor_unit_noise: '20-55',
      outdoor_unit_noise: '50',
      indoor_unit_width: 688,
      outdoor_unit_width: 250,
      outdoor_unit_depth: 180,

      add_functions: [
        'Wi-Fi',
        'Пульт дистанционного управления',
        'Регулировка воздушного потока',
        'Регулировка скорости вращения вентилятара 5 ступ.',
        'Таймер включенияя/выключения',
        'Авторестарт после проподания питания',
        'Турбо-режим',
        'Режим "сон"',
        'Осушение воздуха',
        'Самоочистка',
        'Ионизатор',
        'Антибактериальный фильтр',
      ],

      made_in: 'Китай',
      manufacturer:
        'ТиСиЭл Оверсиас Маркетинг Лимитед, Аламеда Др. Карлос де Ассумпкао, №263, Эдиф. Чайна Сивил Плаза, 5К, Макао, Китай',
      importer: 'ООО "Биоконд", 220020, г. Минск, ул. Короля, 2 оф. 212',
    },
    {
      id: 10,
      title: 'Ballu AURORA ON/OFF MDSA-07HRN8',
      category: 'Мобильные',
      square: 50,
      technology: 'Инверторная',
      image: '/../src/assets/images/conditioner4.png',
      image_item: '/../src/assets/images/conditioner_item.png',
      brand: 'Ballu',
      guarantee: 48,
      price: 1178,

      serviced_area: 65,
      mode: 'Охлаждение и вентиляция',
      cooling_temperature: 'от -10 до +53',
      heating_temperature: 'от -20 до +35',
      indoor_unit_noise: '20-55',
      outdoor_unit_noise: '50',
      indoor_unit_width: 688,
      outdoor_unit_width: 250,
      outdoor_unit_depth: 190,

      add_functions: [
        'Wi-Fi',
        'Пульт дистанционного управления',
        'Регулировка воздушного потока',
        'Регулировка скорости вращения вентилятара 5 ступ.',
        'Таймер включенияя/выключения',
        'Авторестарт после проподания питания',
        'Турбо-режим',
        'Режим "сон"',
        'Осушение воздуха',
        'Самоочистка',
        'Ионизатор',
        'Антибактериальный фильтр',
      ],

      made_in: 'Китай',
      manufacturer:
        'ТиСиЭл Оверсиас Маркетинг Лимитед, Аламеда Др. Карлос де Ассумпкао, №263, Эдиф. Чайна Сивил Плаза, 5К, Макао, Китай',
      importer: 'ООО "Биоконд", 220020, г. Минск, ул. Короля, 2 оф. 212',
    },
    {
      id: 11,
      title: 'Chigo Moon Inverter CS-21V3G-B181AY8B',
      category: 'Настенные',
      square: 50,
      technology: 'on/off',
      image: '/../src/assets/images/conditioner1.png',
      image_item: '/../src/assets/images/conditioner_item2.png',
      brand: 'Chigo',
      guarantee: 24,
      price: 2220,

      serviced_area: 50,
      mode: 'Охлаждение',
      cooling_temperature: 'от -10 до +53',
      heating_temperature: 'от -20 до +35',
      indoor_unit_noise: '20-55',
      outdoor_unit_noise: '50',
      indoor_unit_width: 690,
      outdoor_unit_width: 250,
      outdoor_unit_depth: 190,

      add_functions: [
        'Wi-Fi',
        'Пульт дистанционного управления',
        'Регулировка воздушного потока',
        'Регулировка скорости вращения вентилятара 5 ступ.',
        'Таймер включенияя/выключения',
        'Авторестарт после проподания питания',
        'Турбо-режим',
        'Режим "сон"',
        'Осушение воздуха',
        'Самоочистка',
        'Защита от простуды',
        'Подсос свежего воздуха',
      ],

      made_in: 'Россия',
      manufacturer: ' ООО ТиСиЭл Оверсиас Маркетинг, г,Москва, ул. Пушкинская, д. 4, офис 403',
      importer: 'ООО "Биоконд", 220020, г. Минск, ул. Короля, 2 оф. 212',
    },
    {
      id: 12,
      title: 'MDV Moon Inverter CS-21V3G-B18',
      category: 'Настенные',
      square: 50,
      technology: 'Инверторная',
      image: '/../src/assets/images/conditioner1.png',
      image_item: '/../src/assets/images/conditioner_item.png',
      brand: 'MDV',
      guarantee: 24,
      price: 1205,

      serviced_area: 65,
      mode: 'Охлаждение',
      cooling_temperature: 'от -10 до +53',
      heating_temperature: 'от -20 до +35',
      indoor_unit_noise: '20-55',
      outdoor_unit_noise: '50',
      indoor_unit_width: 690,
      outdoor_unit_width: 250,
      outdoor_unit_depth: 190,

      add_functions: [
        'Wi-Fi',
        'Пульт дистанционного управления',
        'Регулировка воздушного потока',
        'Регулировка скорости вращения вентилятара 5 ступ.',
        'Таймер включенияя/выключения',
        'Авторестарт после проподания питания',
        'Турбо-режим',
        'Режим "сон"',
        'Осушение воздуха',
        'Самоочистка',
        'Защита от простуды',
      ],

      made_in: 'Россия',
      manufacturer: ' ООО ТиСиЭл Оверсиас Маркетинг, г,Москва, ул. Пушкинская, д. 4, офис 403',
      importer: 'ООО "Биоконд", 220020, г. Минск, ул. Короля, 2 оф. 212',
    },
    {
      id: 13,
      title: 'TCL Moon Inverter CS-21V3G-B18',
      category: 'Настенные',
      square: 50,
      technology: 'Инверторная',
      image: '/../src/assets/images/conditioner1.png',
      image_item: '/../src/assets/images/conditioner_item.png',
      brand: 'TCL',
      guarantee: 36,
      price: 1199,

      serviced_area: 60,
      mode: 'Охлаждение',
      cooling_temperature: 'от -25 до +53',
      heating_temperature: 'от -20 до +35',
      indoor_unit_noise: '20-55',
      outdoor_unit_noise: '40',
      indoor_unit_width: 670,
      outdoor_unit_width: 250,
      outdoor_unit_depth: 190,

      add_functions: [
        'Wi-Fi',
        'Пульт дистанционного управления',
        'Регулировка воздушного потока',
        'Регулировка скорости вращения вентилятара 5 ступ.',
        'Таймер включенияя/выключения',
        'Авторестарт после проподания питания',
        'Турбо-режим',
        'Режим "сон"',
        'Осушение воздуха',
        'Самоочистка',
        'Защита от простуды',
      ],

      made_in: 'Россия',
      manufacturer: ' ООО ТиСиЭл Оверсиас Маркетинг, г,Москва, ул. Пушкинская, д. 4, офис 403',
      importer: 'ООО "Биоконд", 220020, г. Минск, ул. Короля, 2 оф. 212',
    },
    {
      id: 14,
      title: 'Chigo Moon Inverter CS-21V3G-B181AY8B',
      category: 'Настенные',
      square: 20,
      technology: 'on/off',
      image: '/../src/assets/images/conditioner4.png',
      image_item: '/../src/assets/images/conditioner_item.png',
      brand: 'Chigo',
      guarantee: 36,
      price: 2730,

      serviced_area: 40,
      mode: 'Охлаждение',
      cooling_temperature: 'от -20 до +53',
      heating_temperature: 'от -20 до +35',
      indoor_unit_noise: '20-55',
      outdoor_unit_noise: '50',
      indoor_unit_width: 690,
      outdoor_unit_width: 250,
      outdoor_unit_depth: 190,

      add_functions: [
        'Wi-Fi',
        'Пульт дистанционного управления',
        'Регулировка воздушного потока',
        'Регулировка скорости вращения вентилятара 5 ступ.',
        'Таймер включенияя/выключения',
        'Авторестарт после проподания питания',
        'Турбо-режим',
        'Режим "сон"',
        'Осушение воздуха',
        'Самоочистка',
        'Защита от простуды',
      ],

      made_in: 'Россия',
      manufacturer: ' ООО ТиСиЭл Оверсиас Маркетинг, г,Москва, ул. Пушкинская, д. 4, офис 403',
      importer: 'ООО "Биоконд", 220020, г. Минск, ул. Короля, 2 оф. 212',
    },
    {
      id: 15,
      title: 'MDV Moon Inverter CS-21V3G-B181AY8B',
      category: 'Настенные',
      square: 25,
      technology: 'Инверторная',
      image: '/../src/assets/images/conditioner3.png',
      image_item: '/../src/assets/images/conditioner_item2.png',
      brand: 'MDV',
      guarantee: 12,
      price: 4250,

      serviced_area: 40,
      mode: 'Охлаждение',
      cooling_temperature: 'от -20 до +53',
      heating_temperature: 'от -20 до +35',
      indoor_unit_noise: '20-55',
      outdoor_unit_noise: '50',
      indoor_unit_width: 690,
      outdoor_unit_width: 250,
      outdoor_unit_depth: 190,

      add_functions: [
        'Wi-Fi',
        'Пульт дистанционного управления',
        'Регулировка воздушного потока',
        'Регулировка скорости вращения вентилятара 5 ступ.',
        'Таймер включенияя/выключения',
        'Авторестарт после проподания питания',
        'Турбо-режим',
        'Режим "сон"',
        'Осушение воздуха',
        'Самоочистка',
        'Защита от простуды',
      ],

      made_in: 'Россия',
      manufacturer: ' ООО ТиСиЭл Оверсиас Маркетинг, г,Москва, ул. Пушкинская, д. 4, офис 403',
      importer: 'ООО "Биоконд", 220020, г. Минск, ул. Короля, 2 оф. 212',
    },
    {
      id: 16,
      title: 'Ballu AURORA ON/OFF MDSA-07HRN8',
      category: 'Мобильные',
      square: 35,
      technology: 'on/off',
      image: '/../src/assets/images/conditioner3.png',
      image_item: '/../src/assets/images/conditioner_item3.png',
      brand: 'Ballu',
      guarantee: 24,
      price: 1719,

      serviced_area: 20,
      mode: 'Обогрев и охлаждение',
      cooling_temperature: 'от -20 до +53',
      heating_temperature: 'от -20 до +35',
      indoor_unit_noise: '20-50',
      outdoor_unit_noise: '50',
      indoor_unit_width: 690,
      outdoor_unit_width: 250,
      outdoor_unit_depth: 190,

      add_functions: [
        'Wi-Fi',
        'Пульт дистанционного управления',
        'Регулировка воздушного потока',
        'Регулировка скорости вращения вентилятара 5 ступ.',
        'Таймер включенияя/выключения',
        'Авторестарт после проподания питания',
        'Турбо-режим',
        'Режим "сон"',
        'Осушение воздуха',
        'Самоочистка',
        'Антибактериальный фильтр',
      ],

      made_in: 'Германия',
      manufacturer: ' ООО ТиСиЭл Оверсиас Маркетинг, г. Берлин, ул. Пушкинская, д. 4, офис 403',
      importer: 'ООО "Биоконд", 220020, г. Минск, ул. Короля, 2 оф. 212',
    },
    {
      id: 17,
      title: 'Chigo Moon Inverter CS-21V3G-B181AY8B',
      category: 'Настенные',
      square: 25,
      technology: 'Инверторная',
      image: '/../src/assets/images/conditioner4.png',
      image_item: '/../src/assets/images/conditioner_item2.png',
      brand: 'Chigo',
      guarantee: 12,
      price: 2800,

      serviced_area: 25,
      mode: 'Обогрев и охлаждение',
      cooling_temperature: 'от -20 до +50',
      heating_temperature: 'от -20 до +30',
      indoor_unit_noise: '22-50',
      outdoor_unit_noise: '50',
      indoor_unit_width: 690,
      outdoor_unit_width: 200,
      outdoor_unit_depth: 190,

      add_functions: [
        'Wi-Fi',
        'Пульт дистанционного управления',
        'Регулировка воздушного потока',
        'Регулировка скорости вращения вентилятара 5 ступ.',
        'Таймер включенияя/выключения',
        'Авторестарт после проподания питания',
        'Турбо-режим',
        'Режим "сон"',
        'Осушение воздуха',
        'Самоочистка',
        'Антибактериальный фильтр',
      ],

      made_in: 'Германия',
      manufacturer: ' ООО ТиСиЭл Оверсиас Маркетинг, г. Берлин, ул. Пушкинская, д. 4, офис 403',
      importer: 'ООО "Биоконд", 220020, г. Минск, ул. Короля, 2 оф. 212',
    },
    {
      id: 18,
      title: 'MDV Moon Inverter CS-21V3G',
      category: 'Мобильные',
      square: 50,
      technology: 'Инверторная',
      image: '/../src/assets/images/conditioner4.png',
      image_item: '/../src/assets/images/conditioner_item.png',
      brand: 'MDV',
      guarantee: 24,
      price: 1803,

      serviced_area: 30,
      mode: 'Обогрев и охлаждение',
      cooling_temperature: 'от -20 до +50',
      heating_temperature: 'от -20 до +30',
      indoor_unit_noise: '22-50',
      outdoor_unit_noise: '50',
      indoor_unit_width: 690,
      outdoor_unit_width: 250,
      outdoor_unit_depth: 190,

      add_functions: [
        'Wi-Fi',
        'Пульт дистанционного управления',
        'Регулировка воздушного потока',
        'Регулировка скорости вращения вентилятара 5 ступ.',
        'Таймер включенияя/выключения',
        'Авторестарт после проподания питания',
        'Турбо-режим',
        'Режим "сон"',
        'Осушение воздуха',
        'Самоочистка',
        'Антибактериальный фильтр',
      ],

      made_in: 'Германия',
      manufacturer: ' ООО ТиСиЭл Оверсиас Маркетинг, г. Берлин, ул. Пушкинская, д. 4, офис 403',
      importer: 'ООО "Биоконд", 220020, г. Минск, ул. Короля, 2 оф. 212',
    },
    {
      id: 19,
      title: 'Haeir Moon Inverter CS-21V3G-B18',
      category: 'Настенные',
      square: 35,
      technology: 'on/off',
      image: '/../src/assets/images/conditioner3.png',
      image_item: '/../src/assets/images/conditioner_item3.png',
      brand: 'Haeir',
      guarantee: 36,
      price: 1938,

      serviced_area: 30,
      mode: 'Обогрев',
      cooling_temperature: 'от -20 до +50',
      heating_temperature: 'от -20 до +30',
      indoor_unit_noise: '22-50',
      outdoor_unit_noise: '50',
      indoor_unit_width: 690,
      outdoor_unit_width: 250,
      outdoor_unit_depth: 190,

      add_functions: [
        'Wi-Fi',
        'Пульт дистанционного управления',
        'Регулировка воздушного потока',
        'Регулировка скорости вращения вентилятара 5 ступ.',
        'Таймер включенияя/выключения',
        'Авторестарт после проподания питания',
        'Турбо-режим',
        'Режим "сон"',
        'Осушение воздуха',
        'Самоочистка',
        'Антибактериальный фильтр',
      ],

      made_in: 'Китай',
      manufacturer:
        'ТиСиЭл Оверсиас Маркетинг Лимитед, Аламеда Др. Карлос де Ассумпкао, №263, Эдиф. Чайна Сивил Плаза, 5К, Макао, Китай',
      importer: 'ООО "Биоконд", 220020, г. Минск, ул. Короля, 2 оф. 212',
    },
    {
      id: 20,
      title: 'Chigo Moon Inverter CS-21V3G-B181AY8B',
      category: 'Настенные',
      square: 25,
      technology: 'on/off',
      image: '/../src/assets/images/conditioner4.png',
      image_item: '/../src/assets/images/conditioner_item.png',
      brand: 'Chigo',
      guarantee: 36,
      price: 2160,

      serviced_area: 25,
      mode: 'Охлаждение',
      cooling_temperature: 'от -20 до +50',
      heating_temperature: 'от -20 до +30',
      indoor_unit_noise: '22-50',
      outdoor_unit_noise: '50',
      indoor_unit_width: 590,
      outdoor_unit_width: 250,
      outdoor_unit_depth: 190,

      add_functions: [
        'Wi-Fi',
        'Пульт дистанционного управления',
        'Регулировка воздушного потока',
        'Регулировка скорости вращения вентилятара 5 ступ.',
        'Таймер включенияя/выключения',
        'Авторестарт после проподания питания',
        'Турбо-режим',
        'Режим "сон"',
        'Осушение воздуха',
        'Самоочистка',
        'Антибактериальный фильтр',
      ],

      made_in: 'Китай',
      manufacturer:
        'ТиСиЭл Оверсиас Маркетинг Лимитед, Аламеда Др. Карлос де Ассумпкао, №263, Эдиф. Чайна Сивил Плаза, 5К, Макао, Китай',
      importer: 'ООО "Биоконд", 220020, г. Минск, ул. Короля, 2 оф. 212',
    },
    {
      id: 21,
      title: 'MDV Moon Inverter CS-21V3G',

      category: 'Настенные',
      square: 50,
      technology: 'Инверторная',
      image: '/../src/assets/images/conditioner3.png',
      image_item: '/../src/assets/images/conditioner_item3.png',
      brand: 'MDV',
      guarantee: 24,
      price: 1805,

      serviced_area: 60,
      mode: 'Охлаждение и обогрев',
      cooling_temperature: 'от -20 до +50',
      heating_temperature: 'от -20 до +30',
      indoor_unit_noise: '22-50',
      outdoor_unit_noise: '50',
      indoor_unit_width: 690,
      outdoor_unit_width: 250,
      outdoor_unit_depth: 190,

      add_functions: [
        'Wi-Fi',
        'Пульт дистанционного управления',
        'Регулировка воздушного потока',
        'Регулировка скорости вращения вентилятара 5 ступ.',
        'Таймер включенияя/выключения',
        'Авторестарт после проподания питания',
        'Турбо-режим',
        'Режим "сон"',
        'Осушение воздуха',
        'Самоочистка',
        'Антибактериальный фильтр',
      ],

      made_in: 'Китай',
      manufacturer:
        'ТиСиЭл Оверсиас Маркетинг Лимитед, Аламеда Др. Карлос де Ассумпкао, №263, Эдиф. Чайна Сивил Плаза, 5К, Макао, Китай',
      importer: 'ООО "Биоконд", 220020, г. Минск, ул. Короля, 2 оф. 212',
    },
    {
      id: 22,
      title: 'Haeir Moon Inverter CS-21V3G-B18',
      category: 'Настенные',
      square: 35,
      technology: 'on/off',
      image: '/../src/assets/images/conditioner3.png',
      image_item: '/../src/assets/images/conditioner_item2.png',
      brand: 'Haeir',
      guarantee: 36,
      price: 3950,

      serviced_area: 25,
      mode: 'Охлаждение и обогрев',
      cooling_temperature: 'от -20 до +50',
      heating_temperature: 'от -20 до +30',
      indoor_unit_noise: '22-40',
      outdoor_unit_noise: '40',
      indoor_unit_width: 690,
      outdoor_unit_width: 160,
      outdoor_unit_depth: 10,

      add_functions: [
        'Wi-Fi',
        'Пульт дистанционного управления',
        'Регулировка воздушного потока',
        'Регулировка скорости вращения вентилятара 5 ступ.',
        'Таймер включенияя/выключения',
        'Авторестарт после проподания питания',
        'Турбо-режим',
        'Режим "сон"',
        'Осушение воздуха',
        'Самоочистка',
      ],

      made_in: 'Китай',
      manufacturer:
        'ТиСиЭл Оверсиас Маркетинг Лимитед, Аламеда Др. Карлос де Ассумпкао, №263, Эдиф. Чайна Сивил Плаза, 5К, Макао, Китай',
      importer: 'ООО "Биоконд", 220020, г. Минск, ул. Короля, 2 оф. 212',
    },

    {
      id: 23,
      title: 'MDV Forest Inverter MDSAF-09HRDN8',
      category: 'Настенные',
      square: 25,
      technology: 'Инверторная',
      image: '/../src/assets/images/conditioner1.png',
      image_item: '/../src/assets/images/conditioner_item.png',
      brand: 'MDV',
      guarantee: 40,
      price: 2680,

      serviced_area: 35,
      mode: 'Охлаждение',
      cooling_temperature: 'от -10 до +53',
      heating_temperature: 'от -20 до +35',
      indoor_unit_noise: '20-55',
      outdoor_unit_noise: '38',
      indoor_unit_width: 698,
      outdoor_unit_width: 255,
      outdoor_unit_depth: 190,
      add_functions: [
        'Wi-Fi',
        'Пульт дистанционного управления',
        'Регулировка воздушного потока',
        'Регулировка скорости вращения вентилятара 5 ступ.',
        'Таймер включенияя/выключения',
        'Авторестарт после проподания питания',
        'Турбо-режим',
        'Режим "сон"',
        'Осушение воздуха',
        'Самоочистка',
      ],

      made_in: 'Россия',
      manufacturer: 'MDV Forest',
      importer: 'MDV Forest',
    },
    {
      id: 24,
      title: 'TCL Elite TAC-09CHSD/XA71IN',
      category: 'Настенные',
      square: 50,
      technology: 'on/off',
      image: '/../src/assets/images/conditioner2.png',
      image_item: '/../src/assets/images/conditioner_item1.png',
      brand: 'TCL',
      guarantee: 40,
      price: 1750,

      serviced_area: 78,
      mode: 'Охлаждение и вентиляция',
      cooling_temperature: 'от -10 до +53',
      heating_temperature: 'от -20 до +35',
      indoor_unit_noise: '20-55',
      outdoor_unit_noise: '38',
      indoor_unit_width: 698,
      outdoor_unit_width: 255,
      outdoor_unit_depth: 190,
      add_functions: [
        'Пульт дистанционного управления',
        'Регулировка воздушного потока',
        'Регулировка скорости вращения вентилятара 5 ступ.',
        'Таймер включенияя/выключения',
        'Режим "сон"',
        'Осушение воздуха',
        'Самоочистка',
        'УФ-лампа',
      ],

      made_in: 'Китай',
      manufacturer:
        'ТиСиЭл Оверсиас Маркетинг Лимитед, Аламеда Др. Карлос де Ассумпкао, №263, Эдиф. Чайна Сивил Плаза, 5К, Макао, Китай',
      importer: 'ООО "Биоконд", 220020, г. Минск, ул. Короля, 2 оф. 212',
    },
    {
      id: 25,
      title: 'Gree AURORA ON/OFF MDSA-07HRN8',
      category: 'Мобильные',
      square: 20,
      technology: 'Инверторная',
      image: '/../src/assets/images/conditioner3.png',
      image_item: '/../src/assets/images/conditioner_item2.png',
      brand: 'Gree',
      guarantee: 20,
      price: 1450,

      serviced_area: 78,
      mode: 'Охлаждение и вентиляция',
      cooling_temperature: 'от -10 до +53',
      heating_temperature: 'от -20 до +35',
      indoor_unit_noise: '20-55',
      outdoor_unit_noise: '30',
      indoor_unit_width: 690,
      outdoor_unit_width: 255,
      outdoor_unit_depth: 180,
      add_functions: [
        'Wi-Fi',
        'Пульт дистанционного управления',
        'Таймер включенияя/выключения',
        'Режим "сон"',
        'Осушение воздуха',
        'Самоочистка',
        'УФ-лампа',
      ],

      made_in: 'Китай',
      manufacturer:
        'ТиСиЭл Оверсиас Маркетинг Лимитед, Аламеда Др. Карлос де Ассумпкао, №263, Эдиф. Чайна Сивил Плаза, 5К, Макао, Китай',
      importer: 'ООО "Биоконд", 220020, г. Минск, ул. Короля, 2 оф. 212',
    },
    {
      id: 26,
      title: 'Gree Moon Inverter CS-21V3G-B181AY8B',
      category: 'Настенные',
      square: 35,
      technology: 'on/off',
      image: '/../src/assets/images/conditioner4.png',
      image_item: '/../src/assets/images/conditioner_item2.png',
      brand: 'Gree',
      guarantee: 24,
      price: 1555,

      serviced_area: 78,
      mode: 'Охлаждение и вентиляция',
      cooling_temperature: 'от -10 до +53',
      heating_temperature: 'от -20 до +35',
      indoor_unit_noise: '20-55',
      outdoor_unit_noise: '40',
      indoor_unit_width: 698,
      outdoor_unit_width: 255,
      outdoor_unit_depth: 170,
      add_functions: [
        'Пульт дистанционного управления',
        'Регулировка воздушного потока',
        'Регулировка скорости вращения вентилятара 5 ступ.',
        'Таймер включенияя/выключения',
        'Авторестарт после проподания питания',
        'Турбо-режим',
        'Режим "сон"',
        'Осушение воздуха',
        'Самоочистка',
        'Подсос свежего воздуха',
      ],

      made_in: 'Китай',
      manufacturer:
        'ТиСиЭл Оверсиас Маркетинг Лимитед, Аламеда Др. Карлос де Ассумпкао, №263, Эдиф. Чайна Сивил Плаза, 5К, Макао, Китай',
      importer: 'ООО "Биоконд", 220020, г. Минск, ул. Короля, 2 оф. 212',
    },
    {
      id: 27,
      title: 'Gree AURORA ON/OFF MDSA-07HRN8',
      category: 'Мобильные',
      square: 20,
      technology: 'Инверторная',
      image: '/../src/assets/images/conditioner1.png',
      image_item: '/../src/assets/images/conditioner_item.png',
      brand: 'Gree',
      guarantee: 12,
      price: 1005,

      serviced_area: 75,
      mode: 'Охлаждение и вентиляция',
      cooling_temperature: 'от -10 до +53',
      heating_temperature: 'от -20 до +35',
      indoor_unit_noise: '20-55',
      outdoor_unit_noise: '50',
      indoor_unit_width: 698,
      outdoor_unit_width: 265,
      outdoor_unit_depth: 200,

      add_functions: [
        'Wi-Fi',
        'Пульт дистанционного управления',
        'Регулировка воздушного потока',
        'Регулировка скорости вращения вентилятара 5 ступ.',
        'Таймер включенияя/выключения',
        'Авторестарт после проподания питания',
        'Турбо-режим',
        'Режим "сон"',
        'Самоочистка',
        'Подсос свежего воздуха',
      ],

      made_in: 'Швеция',
      manufacturer: 'ТиСиЭл Лимитед, Аламеда Др. Карлос де Ассумпкао, №263, Эдиф. , 5К, Макао, Швеция',
      importer: 'ООО "Биоконд", 220020, г. Минск, ул. Короля, 2 оф. 212',
    },
    {
      id: 28,
      title: 'Haeir Moon Inverter CS-21V3G-B181AY8B',
      category: 'Настенные',
      square: 35,
      technology: 'on/off',
      image: '/../src/assets/images/conditioner2.png',
      image_item: '/../src/assets/images/conditioner_item2.png',
      brand: 'Haeir',
      guarantee: 12,
      price: 1009,

      serviced_area: 75,
      mode: 'Охлаждение и вентиляция',
      cooling_temperature: 'от -10 до +53',
      heating_temperature: 'от -20 до +35',
      indoor_unit_noise: '20-55',
      outdoor_unit_noise: '50',
      indoor_unit_width: 508,
      outdoor_unit_width: 255,
      outdoor_unit_depth: 190,

      add_functions: [
        'Wi-Fi',
        'Пульт дистанционного управления',
        'Регулировка воздушного потока',
        'Регулировка скорости вращения вентилятара 5 ступ.',
        'Таймер включенияя/выключения',
        'Авторестарт после проподания питания',
        'Турбо-режим',
        'Режим "сон"',
        'Осушение воздуха',
        'Самоочистка',
        'Подсос свежего воздуха',
      ],

      made_in: 'Швеция',
      manufacturer: 'ТиСиЭл Лимитед, Аламеда Др. Карлос де Ассумпкао, №263, Эдиф. , 5К, Макао, Швеция',
      importer: 'ООО "Биоконд", 220020, г. Минск, ул. Короля, 2 оф. 212',
    },
    {
      id: 29,
      title: 'Ballu AURORA ON/OFF MDSA-07HRN8',
      category: 'Мобильные',
      square: 25,
      technology: 'Инверторная',
      image: '/../src/assets/images/conditioner2.png',
      image_item: '/../src/assets/images/conditioner_item.png',
      brand: 'Ballu',
      guarantee: 12,
      price: 1919,

      serviced_area: 75,
      mode: 'Охлаждение и вентиляция',
      cooling_temperature: 'от -10 до +53',
      heating_temperature: 'от -20 до +35',
      indoor_unit_noise: '20-55',
      outdoor_unit_noise: '50',
      indoor_unit_width: 688,
      outdoor_unit_width: 230,
      outdoor_unit_depth: 170,

      add_functions: [
        'Wi-Fi',
        'Пульт дистанционного управления',
        'Регулировка воздушного потока',
        'Регулировка скорости вращения вентилятара 5 ступ.',
        'Таймер включенияя/выключения',
        'Авторестарт после проподания питания',
        'Турбо-режим',
        'Режим "сон"',
        'Осушение воздуха',
        'Самоочистка',
      ],

      made_in: 'Швеция',
      manufacturer: 'ТиСиЭл Лимитед, Аламеда Др. Карлос де Ассумпкао, №263, Эдиф. , 5К, Макао, Швеция',
      importer: 'ООО "Биоконд", 220020, г. Минск, ул. Короля, 2 оф. 212',
    },
    {
      id: 30,
      title: 'TCL Moon Inverter CS-21V3G-B181AY8B',
      category: 'Настенные',
      square: 20,
      technology: 'on/off',
      image: '/../src/assets/images/conditioner4.png',
      image_item: '/../src/assets/images/conditioner_item.png',
      brand: 'TCL',
      guarantee: 12,
      price: 1018,

      serviced_area: 45,
      mode: 'Охлаждение и вентиляция',
      cooling_temperature: 'от -10 до +53',
      heating_temperature: 'от -20 до +35',
      indoor_unit_noise: '20-55',
      outdoor_unit_noise: '50',
      indoor_unit_width: 688,
      outdoor_unit_width: 250,
      outdoor_unit_depth: 170,

      add_functions: [
        'Wi-Fi',
        'Пульт дистанционного управления',
        'Регулировка воздушного потока',
        'Регулировка скорости вращения вентилятара 5 ступ.',
        'Таймер включенияя/выключения',
        'Авторестарт после проподания питания',
        'Турбо-режим',
        'Режим "сон"',
        'Осушение воздуха',
        'Самоочистка',
        'Подсос свежего воздуха',
      ],

      made_in: 'Китай',
      manufacturer:
        'ТиСиЭл Оверсиас Маркетинг Лимитед, Аламеда Др. Карлос де Ассумпкао, №263, Эдиф. Чайна Сивил Плаза, 5К, Макао, Китай',
      importer: 'ООО "Биоконд", 220020, г. Минск, ул. Короля, 2 оф. 212',
    },
    {
      id: 31,
      title: 'TCL Moon Inverter CS-21V3G-B181AY8B',
      category: 'Настенные',
      square: 35,
      technology: 'Инверторная',
      image: '/../src/assets/images/conditioner3.png',
      image_item: '/../src/assets/images/conditioner_item2.png',
      brand: 'TCL',
      guarantee: 48,
      price: 3118,

      serviced_area: 45,
      mode: 'Охлаждение и вентиляция',
      cooling_temperature: 'от -10 до +53',
      heating_temperature: 'от -20 до +35',
      indoor_unit_noise: '20-55',
      outdoor_unit_noise: '50',
      indoor_unit_width: 688,
      outdoor_unit_width: 250,
      outdoor_unit_depth: 180,

      add_functions: [
        'Wi-Fi',
        'Пульт дистанционного управления',
        'Регулировка воздушного потока',
        'Регулировка скорости вращения вентилятара 5 ступ.',
        'Таймер включенияя/выключения',
        'Авторестарт после проподания питания',
        'Турбо-режим',
        'Режим "сон"',
        'Осушение воздуха',
        'Самоочистка',
        'Подсос свежего воздуха',
      ],

      made_in: 'Китай',
      manufacturer:
        'ТиСиЭл Оверсиас Маркетинг Лимитед, Аламеда Др. Карлос де Ассумпкао, №263, Эдиф. Чайна Сивил Плаза, 5К, Макао, Китай',
      importer: 'ООО "Биоконд", 220020, г. Минск, ул. Короля, 2 оф. 212',
    },
    {
      id: 32,
      title: 'Ballu AURORA ON/OFF MDSA-07HRN8',
      category: 'Мобильные',
      square: 25,
      technology: 'Инверторная',
      image: '/../src/assets/images/conditioner3.png',
      image_item: '/../src/assets/images/conditioner_item.png',
      brand: 'Ballu',
      guarantee: 48,
      price: 4118,

      serviced_area: 65,
      mode: 'Охлаждение и вентиляция',
      cooling_temperature: 'от -10 до +53',
      heating_temperature: 'от -20 до +35',
      indoor_unit_noise: '20-55',
      outdoor_unit_noise: '50',
      indoor_unit_width: 688,
      outdoor_unit_width: 250,
      outdoor_unit_depth: 190,

      add_functions: [
        'Wi-Fi',
        'Пульт дистанционного управления',
        'Регулировка воздушного потока',
        'Регулировка скорости вращения вентилятара 5 ступ.',
        'Таймер включенияя/выключения',
        'Авторестарт после проподания питания',
        'Турбо-режим',
        'Режим "сон"',
        'Осушение воздуха',
        'Самоочистка',
        'Подсос свежего воздуха',
        'УФ-лампа',
      ],

      made_in: 'Китай',
      manufacturer:
        'ТиСиЭл Оверсиас Маркетинг Лимитед, Аламеда Др. Карлос де Ассумпкао, №263, Эдиф. Чайна Сивил Плаза, 5К, Макао, Китай',
      importer: 'ООО "Биоконд", 220020, г. Минск, ул. Короля, 2 оф. 212',
    },
    {
      id: 34,
      title: 'MDV Moon Inverter CS-21V3G-B18',
      category: 'Настенные',
      square: 50,
      technology: 'Инверторная',
      image: '/../src/assets/images/conditioner3.png',
      image_item: '/../src/assets/images/conditioner_item2.png',
      brand: 'MDV',
      guarantee: 24,
      price: 3200,

      serviced_area: 65,
      mode: 'Охлаждение',
      cooling_temperature: 'от -10 до +53',
      heating_temperature: 'от -20 до +35',
      indoor_unit_noise: '20-55',
      outdoor_unit_noise: '50',
      indoor_unit_width: 690,
      outdoor_unit_width: 250,
      outdoor_unit_depth: 190,

      add_functions: [
        'Wi-Fi',
        'Пульт дистанционного управления',
        'Регулировка воздушного потока',
        'Регулировка скорости вращения вентилятара 5 ступ.',
        'Таймер включенияя/выключения',
        'Авторестарт после проподания питания',
        'Турбо-режим',
        'Режим "сон"',
        'Осушение воздуха',
        'Самоочистка',
        'Защита от простуды',
        'Антибактериальный фильтр',
      ],

      made_in: 'Россия',
      manufacturer: ' ООО ТиСиЭл Оверсиас Маркетинг, г,Москва, ул. Пушкинская, д. 4, офис 403',
      importer: 'ООО "Биоконд", 220020, г. Минск, ул. Короля, 2 оф. 212',
    },
    {
      id: 35,
      title: 'Haeir Moon Inverter CS-21V3G-B18',
      category: 'Настенные',
      square: 50,
      technology: 'Инверторная',
      image: '/../src/assets/images/conditioner3.png',
      image_item: '/../src/assets/images/conditioner_item3.png',
      brand: 'Haeir',
      guarantee: 36,
      price: 4105,

      serviced_area: 60,
      mode: 'Охлаждение',
      cooling_temperature: 'от -25 до +53',
      heating_temperature: 'от -20 до +35',
      indoor_unit_noise: '20-55',
      outdoor_unit_noise: '40',
      indoor_unit_width: 670,
      outdoor_unit_width: 250,
      outdoor_unit_depth: 190,

      add_functions: [
        'Wi-Fi',
        'Пульт дистанционного управления',
        'Регулировка воздушного потока',
        'Регулировка скорости вращения вентилятара 5 ступ.',
        'Таймер включенияя/выключения',
        'Авторестарт после проподания питания',
        'Турбо-режим',
        'Режим "сон"',
        'Осушение воздуха',
        'Самоочистка',
        'Защита от простуды',
        'Антибактериальный фильтр',
      ],

      made_in: 'Россия',
      manufacturer: ' ООО ТиСиЭл Оверсиас Маркетинг, г,Москва, ул. Пушкинская, д. 4, офис 403',
      importer: 'ООО "Биоконд", 220020, г. Минск, ул. Короля, 2 оф. 212',
    },
    {
      id: 36,
      title: 'Chigo Moon Inverter CS-21V3G-B181AY8B',
      category: 'Настенные',
      square: 50,
      technology: 'on/off',
      image: '/../src/assets/images/conditioner4.png',
      image_item: '/../src/assets/images/conditioner_item.png',
      brand: 'Chigo',
      guarantee: 36,
      price: 2000,

      serviced_area: 40,
      mode: 'Охлаждение',
      cooling_temperature: 'от -20 до +53',
      heating_temperature: 'от -20 до +35',
      indoor_unit_noise: '20-55',
      outdoor_unit_noise: '50',
      indoor_unit_width: 690,
      outdoor_unit_width: 250,
      outdoor_unit_depth: 190,

      add_functions: [
        'Wi-Fi',
        'Пульт дистанционного управления',
        'Регулировка воздушного потока',
        'Регулировка скорости вращения вентилятара 5 ступ.',
        'Таймер включенияя/выключения',
        'Авторестарт после проподания питания',
        'Турбо-режим',
        'Режим "сон"',
        'Осушение воздуха',
        'Самоочистка',
        'Защита от простуды',
        'Антибактериальный фильтр',
      ],

      made_in: 'Россия',
      manufacturer: ' ООО ТиСиЭл Оверсиас Маркетинг, г,Москва, ул. Пушкинская, д. 4, офис 403',
      importer: 'ООО "Биоконд", 220020, г. Минск, ул. Короля, 2 оф. 212',
    },
    {
      id: 37,
      title: 'MDV Moon Inverter CS-21V3G-B181AY8B',
      category: 'Настенные',
      square: 35,
      technology: 'Инверторная',
      image: '/../src/assets/images/conditioner3.png',
      image_item: '/../src/assets/images/conditioner_item2.png',
      brand: 'MDV',
      guarantee: 12,
      price: 2900,

      serviced_area: 40,
      mode: 'Охлаждение',
      cooling_temperature: 'от -20 до +53',
      heating_temperature: 'от -20 до +35',
      indoor_unit_noise: '20-55',
      outdoor_unit_noise: '50',
      indoor_unit_width: 690,
      outdoor_unit_width: 250,
      outdoor_unit_depth: 190,

      add_functions: [
        'Wi-Fi',
        'Пульт дистанционного управления',
        'Регулировка воздушного потока',
        'Регулировка скорости вращения вентилятара 5 ступ.',
        'Таймер включенияя/выключения',
        'Авторестарт после проподания питания',
        'Турбо-режим',
        'Режим "сон"',
        'Осушение воздуха',
        'Самоочистка',
      ],

      made_in: 'Россия',
      manufacturer: ' ООО ТиСиЭл Оверсиас Маркетинг, г,Москва, ул. Пушкинская, д. 4, офис 403',
      importer: 'ООО "Биоконд", 220020, г. Минск, ул. Короля, 2 оф. 212',
    },
    {
      id: 38,
      title: 'Ballu AURORA ON/OFF MDSA-07HRN8',
      category: 'Мобильные',
      square: 35,
      technology: 'on/off',
      image: '/../src/assets/images/conditioner3.png',
      image_item: '/../src/assets/images/conditioner_item3.png',
      brand: 'Ballu',
      guarantee: 24,
      price: 1999,

      serviced_area: 35,
      mode: 'Обогрев и охлаждение',
      cooling_temperature: 'от -20 до +53',
      heating_temperature: 'от -20 до +35',
      indoor_unit_noise: '20-50',
      outdoor_unit_noise: '50',
      indoor_unit_width: 690,
      outdoor_unit_width: 250,
      outdoor_unit_depth: 190,

      add_functions: [
        'Wi-Fi',
        'Пульт дистанционного управления',
        'Регулировка воздушного потока',
        'Регулировка скорости вращения вентилятара 5 ступ.',
        'Таймер включенияя/выключения',
        'Авторестарт после проподания питания',
        'Турбо-режим',
        'Режим "сон"',
        'Осушение воздуха',
        'Самоочистка',
        'Детектор света',
        'Защита от простуды',
        'Антибактериальный фильтр',
      ],

      made_in: 'Германия',
      manufacturer: ' ООО ТиСиЭл Оверсиас Маркетинг, г. Берлин, ул. Пушкинская, д. 4, офис 403',
      importer: 'ООО "Биоконд", 220020, г. Минск, ул. Короля, 2 оф. 212',
    },
    {
      id: 39,
      title: 'Chigo Moon Inverter CS-21V3G-B181AY8B',
      category: 'Настенные',
      square: 25,
      technology: 'Инверторная',
      image: '/../src/assets/images/conditioner4.png',
      image_item: '/../src/assets/images/conditioner_item.png',
      brand: 'Chigo',
      guarantee: 12,
      price: 2800,

      serviced_area: 40,
      mode: 'Обогрев и охлаждение',
      cooling_temperature: 'от -20 до +50',
      heating_temperature: 'от -20 до +30',
      indoor_unit_noise: '22-50',
      outdoor_unit_noise: '50',
      indoor_unit_width: 690,
      outdoor_unit_width: 200,
      outdoor_unit_depth: 190,

      add_functions: [
        'Wi-Fi',
        'Пульт дистанционного управления',
        'Регулировка воздушного потока',
        'Регулировка скорости вращения вентилятара 5 ступ.',
        'Таймер включенияя/выключения',
        'Авторестарт после проподания питания',
        'Турбо-режим',
        'Режим "сон"',
        'Осушение воздуха',
        'Самоочистка',
        'УФ-лампа',
        'Защита от простуды',
        'Антибактериальный фильтр',
      ],

      made_in: 'Германия',
      manufacturer: ' ООО ТиСиЭл Оверсиас Маркетинг, г. Берлин, ул. Пушкинская, д. 4, офис 403',
      importer: 'ООО "Биоконд", 220020, г. Минск, ул. Короля, 2 оф. 212',
    },
    {
      id: 40,
      title: 'MDV Moon Inverter CS-21V3G',
      category: 'Мобильные',
      square: 25,
      technology: 'Инверторная',
      image: '/../src/assets/images/conditioner2.png',
      image_item: '/../src/assets/images/conditioner_item3.png',
      brand: 'MDV',
      guarantee: 24,
      price: 1810,

      serviced_area: 30,
      mode: 'Обогрев и охлаждение',
      cooling_temperature: 'от -20 до +50',
      heating_temperature: 'от -20 до +30',
      indoor_unit_noise: '22-50',
      outdoor_unit_noise: '50',
      indoor_unit_width: 690,
      outdoor_unit_width: 250,
      outdoor_unit_depth: 190,

      add_functions: [
        'Wi-Fi',
        'Пульт дистанционного управления',
        'Регулировка воздушного потока',
        'Регулировка скорости вращения вентилятара 5 ступ.',
        'Таймер включенияя/выключения',
        'Авторестарт после проподания питания',
        'Турбо-режим',
        'Режим "сон"',
        'Осушение воздуха',
        'Самоочистка',
        'Ионизатор',
        'Защита от простуды',
        'Антибактериальный фильтр',
      ],

      made_in: 'Германия',
      manufacturer: ' ООО ТиСиЭл Оверсиас Маркетинг, г. Берлин, ул. Пушкинская, д. 4, офис 403',
      importer: 'ООО "Биоконд", 220020, г. Минск, ул. Короля, 2 оф. 212',
    },
    {
      id: 41,
      title: 'Haeir Moon Inverter CS-21V3G-B18',
      category: 'Настенные',
      square: 20,
      technology: 'on/off',
      image: '/../src/assets/images/conditioner1.png',
      image_item: '/../src/assets/images/conditioner_item3.png',
      brand: 'Haeir',
      guarantee: 36,
      price: 1950,

      serviced_area: 20,
      mode: 'Обогрев',
      cooling_temperature: 'от -30 до +50',
      heating_temperature: 'от -20 до +30',
      indoor_unit_noise: '22-50',
      outdoor_unit_noise: '50',
      indoor_unit_width: 690,
      outdoor_unit_width: 250,
      outdoor_unit_depth: 190,

      add_functions: [
        'Wi-Fi',
        'Пульт дистанционного управления',
        'Регулировка воздушного потока',
        'Регулировка скорости вращения вентилятара 5 ступ.',
        'Таймер включенияя/выключения',
        'Авторестарт после проподания питания',
        'Турбо-режим',
        'Режим "сон"',
        'Осушение воздуха',
        'Самоочистка',
      ],

      made_in: 'Китай',
      manufacturer:
        'ТиСиЭл Оверсиас Маркетинг Лимитед, Аламеда Др. Карлос де Ассумпкао, №263, Эдиф. Чайна Сивил Плаза, 5К, Макао, Китай',
      importer: 'ООО "Биоконд", 220020, г. Минск, ул. Короля, 2 оф. 212',
    },
    {
      id: 42,
      title: 'MDV Moon Inverter CS-21V3G',
      category: 'Мобильные',
      square: 25,
      technology: 'Инверторная',
      image: '/../src/assets/images/conditioner2.png',
      image_item: '/../src/assets/images/conditioner_item.png',
      brand: 'MDV',
      guarantee: 24,
      price: 1810,

      serviced_area: 30,
      mode: 'Обогрев и охлаждение',
      cooling_temperature: 'от -20 до +50',
      heating_temperature: 'от -20 до +30',
      indoor_unit_noise: '22-50',
      outdoor_unit_noise: '50',
      indoor_unit_width: 690,
      outdoor_unit_width: 250,
      outdoor_unit_depth: 190,

      add_functions: [
        'Wi-Fi',
        'Пульт дистанционного управления',
        'Регулировка воздушного потока',
        'Регулировка скорости вращения вентилятара 5 ступ.',
        'Таймер включенияя/выключения',
        'Авторестарт после проподания питания',
        'Турбо-режим',
        'Режим "сон"',
        'Осушение воздуха',
        'Самоочистка',
        'Ионизатор',
        'Защита от простуды',
        'Антибактериальный фильтр',
      ],

      made_in: 'Германия',
      manufacturer: ' ООО ТиСиЭл Оверсиас Маркетинг, г. Берлин, ул. Пушкинская, д. 4, офис 403',
      importer: 'ООО "Биоконд", 220020, г. Минск, ул. Короля, 2 оф. 212',
    },
    {
      id: 43,
      title: 'MDV Moon Inverter CS-21V3G',
      category: 'Мобильные',
      square: 25,
      technology: 'Инверторная',
      image: '/../src/assets/images/conditioner3.png',
      image_item: '/../src/assets/images/conditioner_item.png',
      brand: 'MDV',
      guarantee: 24,
      price: 1810,

      serviced_area: 30,
      mode: 'Обогрев и охлаждение',
      cooling_temperature: 'от -20 до +50',
      heating_temperature: 'от -20 до +30',
      indoor_unit_noise: '22-50',
      outdoor_unit_noise: '50',
      indoor_unit_width: 690,
      outdoor_unit_width: 250,
      outdoor_unit_depth: 190,

      add_functions: [
        'Wi-Fi',
        'Пульт дистанционного управления',
        'Регулировка воздушного потока',
        'Регулировка скорости вращения вентилятара 5 ступ.',
        'Таймер включенияя/выключения',
        'Авторестарт после проподания питания',
        'Турбо-режим',
        'Режим "сон"',
        'Осушение воздуха',
        'Самоочистка',
        'Ионизатор',
        'Защита от простуды',
        'Антибактериальный фильтр',
      ],

      made_in: 'Германия',
      manufacturer: ' ООО ТиСиЭл Оверсиас Маркетинг, г. Берлин, ул. Пушкинская, д. 4, офис 403',
      importer: 'ООО "Биоконд", 220020, г. Минск, ул. Короля, 2 оф. 212',
    },
    {
      id: 44,
      title: 'MDV Moon Inverter CS-21V3G',
      category: 'Мобильные',
      square: 25,
      technology: 'Инверторная',
      image: '/../src/assets/images/conditioner4.png',
      image_item: '/../src/assets/images/conditioner_item.png',
      brand: 'MDV',
      guarantee: 24,
      price: 1810,

      serviced_area: 30,
      mode: 'Обогрев и охлаждение',
      cooling_temperature: 'от -20 до +50',
      heating_temperature: 'от -20 до +30',
      indoor_unit_noise: '22-50',
      outdoor_unit_noise: '50',
      indoor_unit_width: 690,
      outdoor_unit_width: 250,
      outdoor_unit_depth: 190,

      add_functions: [
        'Wi-Fi',
        'Пульт дистанционного управления',
        'Регулировка воздушного потока',
        'Регулировка скорости вращения вентилятара 5 ступ.',
        'Таймер включенияя/выключения',
        'Авторестарт после проподания питания',
        'Турбо-режим',
        'Режим "сон"',
        'Осушение воздуха',
        'Самоочистка',
        'Ионизатор',
        'Защита от простуды',
        'Антибактериальный фильтр',
      ],

      made_in: 'Германия',
      manufacturer: ' ООО ТиСиЭл Оверсиас Маркетинг, г. Берлин, ул. Пушкинская, д. 4, офис 403',
      importer: 'ООО "Биоконд", 220020, г. Минск, ул. Короля, 2 оф. 212',
    },
  ]);
});

app.listen(PORT, (err) => {
  if (err) {
    console.log(err);
  } else {
    console.log(`Server started on port ${PORT}`);
  }
});
